version: "3.7"

# store all data in an NFS to seperate data and servers
volumes:
  media-data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.123,nolock,soft,rw"
      device: ":media-data/"

services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    dns: 8.8.8.8
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - VERSION=docker
    volumes:
      - /docker/appdata/plex/config:/config
      - /docker/appdata/plex/transcode:/transcode
      - media-data/media/tv:/tv
      - media-data/media/movies:/movies
    restart: unless-stopped

networks:
  default:
    name: media-request-bridge
    driver: bridge