version: "3.7"

# store all data in an NFS to seperate data and servers
volumes:
  media-data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.123,nfsvers=4,nolock,soft,rw"
      device: ":/media-data"

  torrent-downloads:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.123,nfsvers=4,nolock,soft,rw"
      device: ":/media-data/downloads"

services:
  # flaresolverr is a proxy to help bypass Cloudflare and DDoS-GUARD protection
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    dns: 8.8.8.8
    restart: unless-stopped    

  # site/rss indexer that can be connected to sonarr & radarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Europe/London
    volumes:
      - /docker/appdata/prowlarr:/config
    ports:
      - 9696:9696
    dns: 8.8.8.8
    restart: unless-stopped    

  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Europe/London
    dns: 8.8.8.8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - media-data:/data:rw

  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=65534
      - PGID=65534
      - TZ=Europe/London
    dns: 8.8.8.8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - media-data:/data:rw

  qbittorrent:
    container_name: qbittorrent
    environment:
      - PUID=65534
      - PGID=65534
      - QBT_EULA=accept
      - TZ=Europe/London
    image: qbittorrentofficial/qbittorrent-nox:latest
    ports:
      # for bittorrent traffic
      - 6881:6881/tcp
      - 6881:6881/udp
      # for WebUI
      - 8080:8080/tcp
    dns: 8.8.8.8
    read_only: true
    restart: unless-stopped
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - /docker/appdata/qbittorrent:/config
      - torrent-downloads:/data/downloads:rw

  overseerr:
    image: sctx/overseerr:latest
    dns: 8.8.8.8
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/London
      - PORT=5055
    ports:
      - 80:5055
    volumes:
      - /docker/appdata/overseerr:/app/config
    restart: unless-stopped

networks:
  default:
    name: media-request-bridge
    driver: bridge