version: '3.5'

services:
  scrypted:
    environment:
      - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer SET_THIS_TO_SOME_RANDOM_TEXT
      - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update

    volumes:
      # Volume for the Scrypted database.
      - /docker/scrypted/volume:/server/volume
    networks:
      - proxy-bridge
      - default

    ports:
      - 11080:11080
      - 10443:10443

    devices: []

    # uncomment the common systems devices to pass
    # them through to docker.

    # all usb devices, such as coral tpu
    # "/dev/bus/usb:/dev/bus/usb",

    # hardware accelerated video decoding, opencl, etc.
    # "/dev/dri:/dev/dri",

    # uncomment below as necessary.
    # zwave usb serial device

    # "/dev/ttyACM0:/dev/ttyACM0",

    # coral PCI devices
    # "/dev/apex_0:/dev/apex_0",
    # "/dev/apex_1:/dev/apex_1",
    container_name: scrypted
    restart: unless-stopped
    image: koush/scrypted

    # logging is noisy and will unnecessarily wear on flash storage.
    # scrypted has per device in memory logging that is preferred.
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    labels:
      - 'com.centurylinklabs.watchtower.scope=scrypted'

  # watchtower manages updates for Scrypted.
  watchtower:
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=f21c2364-6483-4ba8-bd01-126e4083332d
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_SCOPE=scrypted
      # remove the following line to never allow docker to auto update.
      # this is not recommended.
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
    image: containrrr/watchtower
    container_name: scrypted-watchtower
    restart: unless-stopped
    volumes:
      - /docker/watchtower/var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'com.centurylinklabs.watchtower.scope=scrypted'
    ports:
      # The auto update port 10444 can be configured
      # Must match the port in the auto update url above.
      - 10444:8080
    networks:
      - proxy-bridge
      - default
    # check for updates once an hour (interval is in seconds)
    command: --interval 3600 --cleanup --scope scrypted

# create a dedicated bridge for the stack
networks:
  default:
    name: scrypted-stack-bridge
    driver: bridge

  proxy-bridge:
    name: proxy-bridge
    external: true
